export const tableColumnKeys = [
  { date: 'Date' },
  { departure_airport: 'Departure Airport' },
  { departure_time: 'Departure Time' },
  { destination_airport: 'Destination Airport' },
  { destination_time: 'Destination Time' },
  { aircraft_model: 'Aircraft Model' },
  { aircraft_registration: 'Aircraft Registration' },
  { single_engine_time: 'Single Engine Time' },
  { multi_engine_time: 'Multi Engine Time' },
  { multi_pilot_time: 'Multi Pilot Time' },
  { total_flight_time: 'Total Flight Time' },
  { pic_name: 'PIC Name' },
  { landings_day: 'Landings Day' },
  { landings_night: 'Landings Night' },
  { operational_night_time: 'Operational Night Time' },
  { operational_ifr_time: 'Operational IFR Time' },
  { pic_time: 'PIC Time' },
  { co_pilot_time: 'Co Pilot Time' },
  { dual_time: 'Dual Time' },
  { instructor_time: 'Instructor Time' },
  { simulator_date: 'Simulator Date' },
  { simulator_type: 'Simulator Type' },
  { simulator_time: 'Simulator Time' },
  { remarks: 'Remarks' },
  { type_of_flight: 'Type Of Flight' },
  { page_num: 'Page Number' },
  { route: 'Route' },
];

export const typeOfFlightEnum = [
  'PPL Training',
  'PPL Checkride',
  'PPL Refresher',
  'IFR Training',
  'IFR Refresher',
  'IFR Checkride',
  'CPL Training',
  'CPL Refresher',
  'CPL Checkride',
  'UPRT Training',
  'MEP Training',
  'MEP Refresher',
  'MEP Checkride',
  'MEP IFR Training',
  'MEP IFR Refresher',
  'MEP IFR Checkride',
  'Night VFR',
  'Night IFR',
  'Cross Country VFR',
  'Cross Country IFR',
];

export const searchOperators = ['=', '<', '>', '<=', '>=', '<>'];
